ui: mocha-bdd
browsers:
  - name: internet explorer
    version: 11..latest
  - name: microsoftedge
    version: latest
  - name: safari
    version: latest
  - name: chrome
    version: [latest]
  - name: firefox
    version: [latest]
